CREATE TABLE `rips_patient_services` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `patient_id` bigint unsigned NOT NULL,
  `tenant_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `doctor_id` bigint unsigned DEFAULT NULL,
  `billing_document_id` bigint unsigned DEFAULT NULL,
  `has_incapacity` tinyint(1) NOT NULL DEFAULT '0',
  `requires_fev` tinyint(1) NOT NULL DEFAULT '0',
  `service_datetime` datetime NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `status_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rips_patient_services_patient_id_foreign` (`patient_id`),
  KEY `rips_patient_services_tenant_id_foreign` (`tenant_id`),
  KEY `rips_patient_services_doctor_id_foreign` (`doctor_id`),
  KEY `rips_patient_services_billing_document_id_foreign` (`billing_document_id`),
  KEY `rips_patient_services_status_id_foreign` (`status_id`),
  CONSTRAINT `rips_patient_services_billing_document_id_foreign` FOREIGN KEY (`billing_document_id`) REFERENCES `rips_billing_documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rips_patient_services_doctor_id_foreign` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`),
  CONSTRAINT `rips_patient_services_patient_id_foreign` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rips_patient_services_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `rips_statuses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rips_patient_services_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rips_patient_service_procedures` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rips_patient_service_id` bigint unsigned NOT NULL,
  `rips_admission_route_id` bigint unsigned DEFAULT NULL,
  `rips_service_group_mode_id` bigint unsigned DEFAULT NULL,
  `rips_service_group_id` bigint unsigned DEFAULT NULL,
  `rips_service_id` bigint unsigned DEFAULT NULL,
  `rips_collection_concept_id` bigint unsigned DEFAULT NULL,
  `rips_technology_purpose_id` bigint unsigned DEFAULT NULL,
  `mipres_id` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authorization_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rips_cups_id` bigint unsigned NOT NULL,
  `cie10_id` bigint unsigned DEFAULT NULL,
  `surgery_cie10_id` bigint unsigned DEFAULT NULL,
  `rips_complication_cie10_id` bigint unsigned DEFAULT NULL,
  `service_value` double DEFAULT NULL,
  `copayment_value` double DEFAULT NULL,
  `copayment_receipt_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rips_patient_service_procedures_rips_patient_service_id_foreign` (`rips_patient_service_id`),
  KEY `rips_patient_service_procedures_cups_id_foreign` (`rips_cups_id`),
  KEY `rips_patient_service_procedures_cie10_id_foreign` (`cie10_id`),
  KEY `rips_patient_service_procedures_surgery_cie10_id_foreign` (`surgery_cie10_id`),
  KEY `fk_psp_admission_route` (`rips_admission_route_id`),
  KEY `fk_psp_service_group_mode` (`rips_service_group_mode_id`),
  KEY `fk_psp_service_group` (`rips_service_group_id`),
  KEY `fk_psp_collection_concept` (`rips_collection_concept_id`),
  KEY `fk_psp_complication_cie10` (`rips_complication_cie10_id`),
  KEY `fk_psp_technology_purpose` (`rips_technology_purpose_id`),
  KEY `rips_patient_service_procedures_rips_service_id_foreign` (`rips_service_id`),
  CONSTRAINT `fk_psp_admission_route` FOREIGN KEY (`rips_admission_route_id`) REFERENCES `rips_admission_routes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psp_collection_concept` FOREIGN KEY (`rips_collection_concept_id`) REFERENCES `rips_collection_concepts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psp_complication_cie10` FOREIGN KEY (`rips_complication_cie10_id`) REFERENCES `cie10` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psp_service_group` FOREIGN KEY (`rips_service_group_id`) REFERENCES `rips_service_groups` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psp_service_group_mode` FOREIGN KEY (`rips_service_group_mode_id`) REFERENCES `rips_service_group_modes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psp_technology_purpose` FOREIGN KEY (`rips_technology_purpose_id`) REFERENCES `rips_technology_purposes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rips_patient_service_procedures_cie10_id_foreign` FOREIGN KEY (`cie10_id`) REFERENCES `cie10` (`id`),
  CONSTRAINT `rips_patient_service_procedures_cups_id_foreign` FOREIGN KEY (`rips_cups_id`) REFERENCES `rips_cups` (`id`),
  CONSTRAINT `rips_patient_service_procedures_rips_patient_service_id_foreign` FOREIGN KEY (`rips_patient_service_id`) REFERENCES `rips_patient_services` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rips_patient_service_procedures_rips_service_id_foreign` FOREIGN KEY (`rips_service_id`) REFERENCES `rips_services` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rips_patient_service_procedures_surgery_cie10_id_foreign` FOREIGN KEY (`surgery_cie10_id`) REFERENCES `cie10` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rips_patient_service_consultations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rips_patient_service_id` bigint unsigned NOT NULL,
  `rips_cups_id` bigint unsigned DEFAULT NULL,
  `rips_service_group_id` bigint unsigned DEFAULT NULL,
  `rips_service_group_mode_id` bigint unsigned DEFAULT NULL,
  `rips_service_reason_id` bigint unsigned DEFAULT NULL,
  `rips_consultation_cups_id` bigint unsigned DEFAULT NULL,
  `rips_service_id` bigint unsigned DEFAULT NULL,
  `rips_technology_purpose_id` bigint unsigned DEFAULT NULL,
  `service_value` double DEFAULT NULL,
  `rips_collection_concept_id` bigint unsigned DEFAULT NULL,
  `copayment_value` double DEFAULT NULL,
  `copayment_receipt_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_rps_consultations_service` (`rips_patient_service_id`),
  KEY `rips_patient_service_consultations_cups_id_foreign` (`rips_cups_id`),
  KEY `rips_patient_service_consultations_service_group_id_foreign` (`rips_service_group_id`),
  KEY `rips_patient_service_consultations_service_id_foreign` (`rips_service_id`),
  KEY `rips_patient_service_consultations_technology_purpose_id_foreign` (`rips_technology_purpose_id`),
  KEY `rips_patient_service_consultations_collection_concept_id_foreign` (`rips_collection_concept_id`),
  KEY `fk_rps_group_mode` (`rips_service_group_mode_id`),
  KEY `fk_rps_reason` (`rips_service_reason_id`),
  KEY `fk_rps_consult_cups` (`rips_consultation_cups_id`),
  CONSTRAINT `fk_rps_consult_cups` FOREIGN KEY (`rips_consultation_cups_id`) REFERENCES `rips_cups` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_rps_consultations_service` FOREIGN KEY (`rips_patient_service_id`) REFERENCES `rips_patient_services` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_rps_group_mode` FOREIGN KEY (`rips_service_group_mode_id`) REFERENCES `rips_service_group_modes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_rps_reason` FOREIGN KEY (`rips_service_reason_id`) REFERENCES `rips_service_reasons` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rips_patient_service_consultations_collection_concept_id_foreign` FOREIGN KEY (`rips_collection_concept_id`) REFERENCES `rips_collection_concepts` (`id`),
  CONSTRAINT `rips_patient_service_consultations_cups_id_foreign` FOREIGN KEY (`rips_cups_id`) REFERENCES `rips_cups` (`id`),
  CONSTRAINT `rips_patient_service_consultations_service_group_id_foreign` FOREIGN KEY (`rips_service_group_id`) REFERENCES `rips_service_groups` (`id`),
  CONSTRAINT `rips_patient_service_consultations_service_id_foreign` FOREIGN KEY (`rips_service_id`) REFERENCES `rips_services` (`id`),
  CONSTRAINT `rips_patient_service_consultations_technology_purpose_id_foreign` FOREIGN KEY (`rips_technology_purpose_id`) REFERENCES `rips_technology_purposes` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rips_patient_service_consultation_diagnoses` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rips_patient_service_consultation_id` bigint unsigned NOT NULL,
  `cie10_id` bigint unsigned NOT NULL,
  `rips_diagnosis_type_id` bigint unsigned DEFAULT NULL,
  `sequence` smallint unsigned NOT NULL COMMENT '1 = principal, 2+ = relacionados',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_rps_consultation_diagnoses` (`rips_patient_service_consultation_id`),
  KEY `rips_patient_service_consultation_diagnoses_cie10_id_foreign` (`cie10_id`),
  KEY `fk_consult_diag_type` (`rips_diagnosis_type_id`),
  CONSTRAINT `fk_consult_diag_type` FOREIGN KEY (`rips_diagnosis_type_id`) REFERENCES `rips_diagnosis_types` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_rps_consultation_diagnoses` FOREIGN KEY (`rips_patient_service_consultation_id`) REFERENCES `rips_patient_service_consultations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rips_patient_service_consultation_diagnoses_cie10_id_foreign` FOREIGN KEY (`cie10_id`) REFERENCES `cie10` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;